name: C++ Auto Build and Run

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile and Run All CPP Files
      shell: powershell
      run: |
        Get-ChildItem -Filter *.cpp | ForEach-Object {
          $file = $_.Name
          $exe = $_.BaseName + ".exe"
          
          Write-Host "---------------------------------------"
          Write-Host "COMPILING: $file"
          
          # Jalankan kompilasi
          cl.exe /EHsc $file
          
          if ($LastExitCode -eq 0) {
            Write-Host "RUNNING: $exe"
            Write-Host "OUTPUT:"
            ./$exe
            Write-Host ""
          } else {
            Write-Host "ERROR: Gagal mengompilasi $file"
            exit 1
          }
        }