name: C++ MSVC Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile tester.cpp
      run: cl.exe /EHsc tester.cpp

    - name: Run Program
      run: .\tester.exe